In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("../data/supply_chain.csv")

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully!
Rows: 1000
Columns: 15

In [3]:
df.head()

,Order_ID,Order_Date,Product_ID,Product_Name,Category,Supplier_ID,Supplier_Name,Quantity,Unit_Price,Sales,Stock,Reorder_Level,Delivery_Days,Delivery_Status,Order_Status
0,1001,2025-02-04,P006,Mouse,Accessories,S004,Prime Distributors,18,800,14400,80,26,2,On Time,Delivered
1,1002,2025-12-10,P009,Office Chair,Furniture,S004,Prime Distributors,13,7000,91000,61,20,10,On Time,Delivered
2,1003,2025-09-09,P004,Monitor,Electronics,S005,Reliable Suppliers,9,12000,108000,54,23,5,On Time,Delivered
3,1004,2025-03-09,P009,Office Chair,Furniture,S002,Global Electronics,5,7000,35000,48,20,4,Delayed,Delivered
4,1005,2025-12-26,P008,Printer,Office,S004,Prime Distributors,18,15000,270000,68,27,7,Delayed,Delivered

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         1000 non-null   int64
 1   Order_Date       1000 non-null   object
 2   Product_ID       1000 non-null   object
 3   Product_Name     1000 non-null   object
 4   Category         1000 non-null   object
 5   Supplier_ID      1000 non-null   object
 6   Supplier_Name    1000 non-null   object
 7   Quantity         1000 non-null   int64
 8   Unit_Price       1000 non-null   int64
 9   Sales            1000 non-null   int64
 10  Stock            1000 non-null   int64
 11  Reorder_Level    1000 non-null   int64
 12  Delivery_Days    1000 non-null   int64
 13  Delivery_Status  1000 non-null   object
 14  Order_Status     1000 non-null   object
dtypes: int64(7), object(8)
memory usage: 117.3+ KB

In [5]:
df.isnull().sum()

Order_ID           0
Order_Date         0
Product_ID         0
Product_Name       0
Category           0
Supplier_ID        0
Supplier_Name      0
Quantity           0
Unit_Price         0
Sales              0
Stock              0
Reorder_Level      0
Delivery_Days      0
Delivery_Status    0
Order_Status       0
dtype: int64

In [6]:
print("Duplicate records:", df.duplicated().sum())

Duplicate records: 0

In [7]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

print(df["Order_Date"].dtype)

datetime64[ns]

In [8]:
df.dtypes

Order_ID                    int64
Order_Date         datetime64[ns]
Product_ID                 object
Product_Name               object
Category                   object
Supplier_ID                object
Supplier_Name              object
Quantity                    int64
Unit_Price                  int64
Sales                       int64
Stock                       int64
Reorder_Level               int64
Delivery_Days               int64
Delivery_Status            object
Order_Status               object
dtype: object

In [9]:
df.describe()

,Order_ID,Order_Date,Quantity,Unit_Price,Sales,Stock,Reorder_Level,Delivery_Days
count,1000.000000,1000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000
mean,1500.500000,2025-06-29 02:02:24,10.592000,14179.200000,150344.000000,52.545000,20.10600,7.145000
min,1001.000000,2025-01-01 00:00:00,1.000000,800.000000,800.000000,5.000000,10.00000,2.000000
25%,1250.750000,2025-03-31 00:00:00,5.000000,2500.000000,20750.000000,28.750000,15.00000,5.000000
50%,1500.500000,2025-06-27 00:00:00,10.500000,12000.000000,84000.000000,53.000000,20.00000,7.000000
75%,1750.250000,2025-10-01 00:00:00,16.000000,18000.000000,201000.000000,76.000000,25.00000,10.000000
max,2000.000000,2025-12-31 00:00:00,20.000000,50000.000000,1000000.000000,100.000000,30.00000,12.000000
std,288.819436,NaN,5.911216,13937.923557,190410.497456,27.458367,6.07418,3.111858

In [10]:
print("Total Sales:", df["Sales"].sum())
print("Average Sales:", df["Sales"].mean())
print("Maximum Sale:", df["Sales"].max())
print("Minimum Sale:", df["Sales"].min())

Total Sales: 150344000
Average Sales: 150344.0
Maximum Sale: 1000000
Minimum Sale: 800

In [11]:
low_stock = df[df["Stock"] < df["Reorder_Level"]]

print("Low Stock Records:", len(low_stock))

low_stock[
    [
        "Product_Name",
        "Stock",
        "Reorder_Level"
    ]
].head(20)

Low Stock Records: 167

     Product_Name  Stock  Reorder_Level
9          Laptop      6             24
13   Office Chair      7             12
14           Desk     21             22
15       Keyboard     20             30
21        Monitor     20             28
26   Mobile Phone     10             27
30          Mouse     17             27
46   Office Chair      5             29
50        Printer     19             20
62         Tablet      5             30
65       Keyboard      7             11
72         Tablet      9             15
81   Office Chair     13             30
84       Keyboard     21             30
91         Tablet     13             24
93           Desk      7             20
102        Tablet     11             29
104  Mobile Phone      8             27
108         Mouse     12             28
111    Headphones      8             21

In [12]:
delayed_orders = df[
    df["Delivery_Status"] == "Delayed"
]

print("Delayed Orders:", len(delayed_orders))

Delayed Orders: 414

In [13]:
delayed_orders[
    [
        "Order_ID",
        "Supplier_Name",
        "Delivery_Days",
        "Delivery_Status"
    ]
].head(20)

    Order_ID       Supplier_Name  Delivery_Days Delivery_Status
3       1004  Global Electronics              4         Delayed
4       1005  Prime Distributors              7         Delayed
5       1006   Tech Supplier Ltd              3         Delayed
6       1007  Global Electronics              5         Delayed
10      1011   Tech Supplier Ltd             10         Delayed
13      1014  Prime Distributors              7         Delayed
15      1016   Tech Supplier Ltd              9         Delayed
16      1017     Smart Supply Co              9         Delayed
17      1018     Smart Supply Co              7         Delayed
18      1019  Reliable Suppliers              6         Delayed
20      1021     Smart Supply Co              6         Delayed
21      1022   Tech Supplier Ltd              5         Delayed
22      1023  Reliable Suppliers              9         Delayed
24      1025  Prime Distributors              2         Delayed
28      1029     Smart Supply Co             11         Delayed
29      1030     Smart Supply Co              4         Delayed
36      1037  Reliable Suppliers              8         Delayed
38      1039  Prime Distributors             12         Delayed
39      1040     Smart Supply Co              9         Delayed
40      1041     Smart Supply Co             11         Delayed

In [14]:
df = df.drop_duplicates()

df.to_csv(
    "../data/cleaned_supply_chain.csv",
    index=False
)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!